services:
  angular-app:
    build:
      context: .
      args:
        - ENV_CONFIGURATION=${ENV_NAME:-dev} 
    container_name: ${CONTAINER_NAME:-zamadev-dev}
    expose:
      - "80"
    networks:
      - proxy_network
    restart: always

networks:
  proxy_network:
    external: true