services:
  angular-app:
    image: ${DOCKERHUB_USERNAME}/zamadev:${IMAGE_TAG}
    container_name: ${CONTAINER_NAME}
    expose:
      - "80"
    networks:
      - proxy_network
    restart: always

networks:
  proxy_network:
    external: true